package cli

import (
	"fmt"
	"log"

	"github.com/spf13/cobra"
	"github.com/sterenczak-marek/notes-app-oauth-stack/oauth_server/internal/models"
)

type UserHandler struct{}

var Email = ""
var Password = ""

func (h *UserHandler) CreateUser(_ *cobra.Command, _ []string) {
	if user := models.GetUserByEmail(Email); user != nil {
		log.Fatalf("User with email=%s already exists\n", Email)
	}

	var echoPassword bool
	if Password == "" {
		Password = generateSecret(26)
		echoPassword = true
	}

	user := &models.User{
		Email:    Email,
		Password: Password,
	}
	if err := user.Create(); err != nil {
		log.Panicf("Failed to create user: %s", err)
	}
	user = models.GetUserByEmail(Email)
	fmt.Printf("Created OAuth server user: \nUUID: %s\nEmail: %s\n", user.UUID, user.Email)
	if echoPassword {
		fmt.Printf("Autogenerated password: %s\n", Password)
	}
}
